### ISSUE TITLE
Solver팀의 스켈레톤 코드 작성하기

### ISSUE THREAD

**Issue by LightAllWorld** [LightAllWorld/Hidato_Puzzle#5]
Solver 팀의 스켈레톤 작성이 완료되면 알려주세요

**Comment by LightAllWorld** [comment]
스켈레톤 코드 확인 결과, 무슨 파일이 무슨 역할을 하는지 모르겠음 솔버팀은 설명좀요

**Comment by KMUKKS** [comment]
현재 스켈레톤 코드 유형이 두가지가 있는데, 어떤 코드의 내용이 이해가 안가시나요 팀장님?

**Comment by KMUKKS** [comment]
일단 현재 스켈레톤 코드 유형이 skeleton.cpp , (solver.h,main.cpp) 두 유형으로 나뉘어져 있는데 두가지 방향으로 형태가 나와서 그에 맞춰서 구현하려고 하는 겁니다.
