### ISSUE TITLE
solver팀의 floodFill 알고리즘에서 중간값이 바뀌는 상황

### ISSUE THREAD

**Issue by KMUKKS** [LightAllWorld/Hidato_Puzzle#7]
첫 starting Node를 잘 찾아서 탐색하다가 제너레이터에서 받은 중간값 들이 바뀌는 상황인데

도와주세요 solver팀

**Comment by dnap512** [comment]
노드 9번째에서 10으로갈때 10으로 가지않고 중간값 11을 10으로 수정해서 먹어버리는 상황을 발견했습니다.
해당 부분 코드 조건식이 현재좌표값이 현재순서의 중간값 인지만을 검사하고, 실제 진행되고 있는 값(orderOfMat)이 중간값과 같은지를 비교하지 않았네요.
따라서 조건식 추가해서 수정했습니다

**Comment by KMUKKS** [comment]
해결되었습니다.
